### ISSUE TITLE
Does not compile with span of bool type

### ISSUE THREAD

**Issue by stayprivate** [tcbrindle/span#24]
gcc 9.2 trying to replace gsl::span with tcb::span I'm getting compiler errors when the a container is of type std::vector<bool>

void array(std::string_view tag, tcb::span<const bool> value)
...
{
   array(tag, tcb::span<const bool>(val,nbElem),);  // gazillions of error are generated here.  No issue if the type of the span is integer

**Comment by tcbrindle** [comment]
If I understand correctly, you're trying to use `tcb::span<bool>`, instantiated from a `std::vector<bool>`?

If so, that isn't going to work, due to the fact that `std::vector<bool>` is not contiguous.

This doesn't seem to generate "gazillions of errors" for me at least ([example](https://godbolt.org/z/6WAcV8)), so perhaps you're doing something different?

**Comment by stayprivate** [comment]
Thanks for the reply.

Reading the doc on vector it is not clear to me if contiguous applies to
the specialization of vector <bool>. All I know for sure is that the
gsl::span implementation supports it. I don't have the code with me right
to figure out why.

I might have exaggerated the gazillion thing. But in real code I have more
than 1000 lines of errors 😉

Le lun. 6 janv. 2020 17 h 01, Tristan Brindle <notifications@github.com> a
écrit :

**Comment by stayprivate** [comment]
Tristan,

I got it totally wrong. Check https://godbolt.org/z/uXraMV. The issue seems to be coming from some implicit conversion of containers. gsl seems to have a check to prevent constructor to be used if the type is not sequential.  Because the pointer return by std::vector<bool>::data() is of type void it prevents this constructor from being selected, I think.

```
// construct from containers
// future: could use contiguous_iterator_traits to identify only contiguous containers
// type-requirements: container must have .size(), operator[] which are value_type compatible
template<typename Cont, typename DataType = typename Cont::value_type,
	 typename = std::enable_if_t<
	 !details::is_span<Cont>::value && std::is_convertible<DataType (*)[], value_type (*)[]>::value &&
	 std::is_same<std::decay_t<decltype(std::declval<Cont>().size(), *std::declval<Cont>().data())>, DataType>::value>>
constexpr span(Cont &cont)
: span(static_cast<pointer>(cont.data()), details::newBoundsHelper<bounds_type>(static_cast<size_type>(cont.size())))
{
}
``

```

**Comment by tcbrindle** [comment]
Ah, I see the problem now. `vector<bool>` cannot be converted to `span<bool>`, but we're giving a hard error when doing the check rather than gracefully SFINAE-ing -- see [here](https://godbolt.org/z/Hxnkvc) for another example. I'll fix it.

**Comment by tcbrindle** [comment]
I wonder why libstdc++'s `vector<bool>` has a `data()` member, even though it's [not supposed to](http://eel.is/c++draft/vector.bool)...

**Comment by tcbrindle** [comment]
@stayprivate This should now be fixed -- please let me know if not. Thanks for the bug report!

**Comment by stayprivate** [comment]
Tristan,
Works fine now, thanks for the quick response!
