### ISSUE TITLE
span.hpp should include <iterator> and <tuple>

### ISSUE THREAD

**Issue by adigostin** [tcbrindle/span#27]
... since it uses [`std::data` from &lt;iterator&gt;](https://en.cppreference.com/w/cpp/iterator/data) and specializes [`tuple_size` from &lt;tuple&gt;](https://en.cppreference.com/w/cpp/utility/tuple/tuple_size).

Not all C++ runtimes include &lt;iterator&gt; and &lt;tuple&gt; via other headers.
Mine doesn't, and if I don't include these two _before_ &lt;span.hpp&gt;, I get compilation errors.

**Comment by tcbrindle** [comment]
According to the C++17 standard, `std::data()` should be available by including `<array>` (see `[iterator.container]`). Likewise, `<array>` should provide the forward declarations of `tuple_size` and `tuple_element` that we need for structured bindings. Which implementation are you using where this is a problem?

**Comment by adigostin** [comment]
Ok, you're right. The implementation is a small subset of C++ written in-house with just a few types that makes sense for us in embedded systems (compiler is the Rowley/Segger distribution of GnuARM 8). I think I'll just add `#include <iterator>` and `#include <tuple>` to our `<array>` and be done with it. Thanks and you can close this.

**Comment by tcbrindle** [comment]
You don't need to include all of `<tuple>` -- the forward declarations of `tuple_size` and `tuple_element` should be enough.
