### ISSUE TITLE
p1872r0 has not been implemented (replacing index_type with size_type)

### ISSUE THREAD

**Issue by brandl-muc** [tcbrindle/span#30]
I just realized that your `span` implementation is missing the nested typedef `using size_type = std::size_t`. A [bit of investigation](https://stackoverflow.com/questions/55209261/why-does-stdspan-lack-size-type) showed that [P1872R0](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1872r0.pdf) was adopted in Belfast and changed `index_type` to `size_type`. Consequently it can be found on [cppreference.com](https://en.cppreference.com/w/cpp/container/span) and in [the current draft on eel.is](http://eel.is/c++draft/views#span.overview-2).
Any reason not to adopt this or would a PR be welcome?

**Comment by tcbrindle** [comment]
> Any reason not to adopt this or would a PR be welcome?

No reason other than I missed the change in Belfast. PR welcome :)

**Comment by brandl-muc** [comment]
Good to hear, will deliver this weekend the latest I suppose.

**Comment by tcbrindle** [comment]
All done, thanks for the bug report
