### ISSUE TITLE
Latest C++20 draft has no cbegin/cend/crbegin/crend (anymore)

### ISSUE THREAD

**Issue by al-mission-2016** [tcbrindle/span#35]
Hi, Tristian.

The _Committee_ has expelled the **const versions** of iterators out of std::span.
If you're keeping your `tcb::span` to be C++20 compliant would not it be reasonable to
remove those **const iterators** out of `tcb::span` as well?

I mean "commenting out" (or wraping up in macro conditions) the following code:
```
    constexpr const_iterator cbegin() const noexcept { return begin(); }
    constexpr const_iterator cend() const noexcept { return end(); }
    const_reverse_iterator crbegin() const noexcept ...
    const_reverse_iterator crend() const noexcept ...
```
Сonfirmative links:
[LWG-3320](https://cplusplus.github.io/LWG/issue3320)
[LLVM on std::span](https://reviews.llvm.org/D75642)

**Comment by tcbrindle** [comment]
Thanks for letting me know, I somehow missed this despite being at the Belfast meeting!

It should now be fixed.
