### ISSUE TITLE
Compilation error caused by data() member

### ISSUE THREAD

**Issue by ceztko** [tcbrindle/span#44]
I have an interesting problem. The following code:

```
#include "span.hpp"
#include <vector>

class Test
{
public:
    Test() { }
    Test(const Test&) = default;
    /* explicit */ Test(const tcb::span<const int>&) { } // Making the constructor explicit **doesn't** fix the issue

    Test& operator=(const Test&) = default;
    Test& operator=(const tcb::span<const int>&) { return *this; }

    const std::vector<int>& data() const { return m_data; } // Commenting this member will fix the error

private:
    std::vector<int> m_data;
};

int main()
{
    Test test;
    test = Test();
    return 0;
}
```

Produces the following error on Visual Studio 2019 16.11.7 (any /std:c++xx setting):

```
1>span.hpp(271,1): error C2234: 'abstract declarator': arrays of references are illegal
1>ConsoleApplication1.cpp(28): message : see reference to class template instantiation 'tcb::detail::is_container_element_type_compatible<const Test &,const char,void>' being compiled
```

It also produces a similar error in gcc 9.3.0:
```
/home/ceztko/span.hpp: In instantiation of ‘struct tcb::detail::is_container_element_type_compatible<Test&, const int, void>’:
/home/ceztko/span.hpp:363:75:   required by substitution of ‘template<class Container, long unsigned int E, typename std::enable_if<(((E == tcb::dynamic_extent) && tcb::detail::is_container<Container, typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value) && tcb::detail::is_container_element_type_compatible<Container&, const int, void>::value), int>::type <anonymous> > constexpr tcb::span<const int>::span(Container&) [with Container = Test; long unsigned int E = 18446744073709551615; typename std::enable_if<(((E == tcb::dynamic_extent) && tcb::detail::is_container<Container, typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value) && tcb::detail::is_container_element_type_compatible<Container&, const int, void>::value), int>::type <anonymous> = <missing>]’
test.c++:23:17:   required from here
/home/ceztko/span.hpp:264:8: error: creating array of ‘std::__remove_pointer_helper<const std::vector<int>&, const std::vector<int>&>::type’ {aka ‘const std::vector<int>&’}
  264 | struct is_container_element_type_compatible<
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  265 |     T, E,
      |     ~~~~~
  266 |     typename std::enable_if<
      |     ~~~~~~~~~~~~~~~~~~~~~~~~
  267 |         !std::is_same<typename std::remove_cv<decltype(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  268 |                           detail::data(std::declval<T>()))>::type,
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  269 |                       void>::value>::type>
      |                       ~~~~~~~~~~~~~~~~~~~~
/home/ceztko/span.hpp: In instantiation of ‘struct tcb::detail::is_container_element_type_compatible<const Test&, const int, void>’:
/home/ceztko/span.hpp:374:75:   required by substitution of ‘template<class Container, long unsigned int E, typename std::enable_if<(((E == tcb::dynamic_extent) && tcb::detail::is_container<Container, typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value) && tcb::detail::is_container_element_type_compatible<const Container&, const int, void>::value), int>::type <anonymous> > constexpr tcb::span<const int>::span(const Container&) [with Container = Test; long unsigned int E = 18446744073709551615; typename std::enable_if<(((E == tcb::dynamic_extent) && tcb::detail::is_container<Container, typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>::value) && tcb::detail::is_container_element_type_compatible<const Container&, const int, void>::value), int>::type <anonymous> = <missing>]’
test.c++:23:17:   required from here
/home/ceztko/span.hpp:264:8: error: creating array of ‘std::__remove_pointer_helper<const std::vector<int>&, const std::vector<int>&>::type’ {aka ‘const std::vector<int>&’}
```

If I comment the `data()` member, the problem fixes itself, there's clearly a clash. A similar [code](https://wandbox.org/permlink/1ka9Uta93S1rN0pO) using a supplied `span` in a recent C++20 compliant compiler doesn't show the issue. Fortunately the problem was easy to workaround in my case but a fix would be very welcome since it was quite annoying to debug and it could happen elsewhere, since a `data()` member is to be commonly found.

**Comment by ddevienne** [comment]
Hi. Isn't putting anything in the `std` namespace UB? (except some template specializations).
Do you have the same issue, when you don't do the `using ... tcb` inside `std`, and use `tcb::span` elsewhere?

**Comment by ceztko** [comment]
> Do you have the same issue, when you don't do the using ... tcb inside std, and use tcb::span elsewhere?

Certainly yes. I already reproduced the issue with the `tcb` namespace as well but I abused the language specification to be able to test the very same code on C++20 compilers as I did [here](https://wandbox.org/permlink/1ka9Uta93S1rN0pO). I modified the example to just use the `tcb` namespace, for better clarity.

**Comment by ddevienne** [comment]
Orthogonal to your issue, but why use `span` instead of `std::string_view` in this particular case?
Or you've just used `const char` as an example, but this issue happens with other types as well?
What happens if you make the Ctor taking the `span` be `explicit`? I suspect nothing, just thinking aloud...

**Comment by ceztko** [comment]
> Or you've just used const char as an example, but this issue happens with other types as well?

It happens with other types as well. I updated the example once again for better clarity and deviate this kind of remarks. The issue really seems to be a clash with the `data()` member and a `data` function defined in span.hpp as a replacement for `std::data`.

> What happens if you make the Ctor taking the span be explicit? I suspect nothing, just thinking aloud...

Reproduces as well.

> Orthogonal to your issue, but why use span instead of std::string_view in this particular case?

This is not relevant to the issue, but to answer you in my code I distinguish between use of `string_view` for real UTF-8 encoded strings and `span<const char>` for unknown content buffer view. It helps a lot with API clarity.

**Comment by ceztko** [comment]
I reproduced as well in gcc 9.3.0, where it produces better error traces.

**Comment by ddevienne** [comment]
> for unknown content buffer view

FWIW, for that, I prefer `span<std::byte>`, and I've used the trick used for `std::byte` (to declare it as an `enum class` to avoid all implicit conversions) in several places in my code. That's IMHO much more obvious to convey _text_ is not expected. It's even better than `const unsigned char`, itself better than `const char`. And sorry for my [OT] remarks, I'll keep quiet now. My $0.02. --DD

**Comment by ceztko** [comment]
> I prefer span<std::byte>[...] That's IMHO much more obvious to convey text is not expected

Yes, I know it and I tried to use it couple of years ago. But I would have expected at least implicit coercion from other byte size types (like assigning a `byte` from a `char` or `uint8_t`), which didn't found its way into the standard and it makes it a lot less appealing to use to me. Also an unknown buffer depending on the context often need to be interpreted as a `char` buffer so I decided for a more pragmatic solution. I think this is really a matter of taste and toleration of amount of `static_cast`/C style casting needed. This is also my $0.02.

**Comment by ddevienne** [comment]
Good points. Last remark: Boost 1.78 released today with a `boost::span` implementation.
https://www.boost.org/doc/libs/1_78_0/libs/core/doc/html/core/span.html
But the time we upgrade to Boost 1.78, we'll probably be in C++20 anyways :)

**Comment by tcbrindle** [comment]
Hi @ceztko, thanks for the bug report.

I've got a fix in PR #45 which I think should work. Would you mind trying out [this version](https://raw.githubusercontent.com/tcbrindle/span/fix44/include/tcb/span.hpp) of span.hpp and letting me know if it fixes the issue for you?

**Comment by ceztko** [comment]
Yes, it seems to fix for me in the platforms I already mentioned and in a bigger code base.

**Comment by mkurdej** [comment]
FWIW, I've hit the same problem when using a class that has `const void * data()` member. PR #45 fixes the problem for me.
BTW, I had another workaround that would *probably* not work for this issue (because `data()` doesn't return a pointer type).
The workaround was to add `remove_pointer_t` in the enable_if condition:
```
template <typename T, typename E>
struct is_container_element_type_compatible<T,
    E,
    std::enable_if_t<!std::is_same_v<void, std::remove_cv_t<remove_pointer_t<decltype(detail::data(std::declval<T>()))>>>>>
    : std::is_convertible<remove_pointer_t<decltype(detail::data(std::declval<T>()))> (*)[], E (*)[]>
{};
```
