### ISSUE TITLE
Cannot construct from std::array of const values

### ISSUE THREAD

**Issue by DiegoBaldassarMilleuno** [tcbrindle/span#46]
Your span implementation can be constructed from a constant std::array, but not from a std::array of constant values.

See here: [https://godbolt.org/z/nMPK6fvsh](https://godbolt.org/z/nMPK6fvsh)

**Comment by tcbrindle** [comment]
Thanks, I agree that this is a bug in the implementation -- our constructor from `std::array` does not match the [spec](https://eel.is/c++draft/views.span#span.cons). I suspect this constructor was changed at some point and I missed it.
