### ISSUE TITLE
span type missing const_iterator member type

### ISSUE THREAD

**Issue by graphicsMan** [tcbrindle/span#47]
Great implementation, thanks!  I'm trying to use span with gtest's ElementsAreArray.  Unfortunately since span is missing a const_iterator member type, it won't compile.  It looks like the const iterator begin/end are also missing.  Admittedly, I haven't given this a lot of thought.  Looking at https://en.cppreference.com/w/cpp/container/span I see that the types are missing there also.   Perhaps there is a well thought-out reason?

 Is there a reasonable solution?

**Comment by tcbrindle** [comment]
Hi @graphicsMan, this discussion has been around for nearly as long as `span` itself, and doesn't seem to have finished yet! You're right that in C++20, `span` doesn't have a `const_iterator` member, and doesn't have `cbegin()` or `cend()` functions. However, there have been proposals (e.g. [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2276r1.pdf) and [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2278r2.html)) to change this for C++23.

As this project aims to implement (as closely as possible) the standard specification, at the moment we're doing the right thing by omitting these members. If and when the standard adds them back in, we'll aim to reflect that change here as well.
