### ISSUE TITLE
Compilation error when trying to emplace spans in a vector (while STL span works fine)

### ISSUE THREAD

**Issue by JorgeBlesaGracia** [tcbrindle/span#49]
Hi!
First of all thanks for this work.
While experimenting with this span implementation, I have found a case where this span implementation throws compilation errors while the standard span implementation works fine. At the end of this comment I attach a link to a code snipet reproducing this behaviour.

The particular usage is creating a vector of spans by using subspan method of a span covering the whole memory section.
I had also compilation errors when trying to mix this span implementation with std::vector in other ways.
It would be great if it could be fixed, since it is very useful.

I have prepared a code snipet reproducing this error: 
https://coliru.stacked-crooked.com/a/dafe684fef821f75
By commenting/uncommenting   #define USE_STD_SPAN  one can use either this implementation (copy/pasted from this repository with the namespace changed to WRE::Utils), or use the STL C++20 implementation of span.

Thank you very much in advance.

**Comment by tcbrindle** [comment]
Thanks for the bug report. This should have been fixed by #50 (thanks @kimci86!).
